version: "3"
services:        
  selenium-hub-bad:
    image: selenium/hub:4.13.0
    container_name: selenium-hub-bad
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=30

  selenium-node-chrome1:
    image: selenium/node-chrome:4.13.0
    shm_size: 2g
    depends_on:
      - selenium-hub-bad
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_EVENT_BUS_HOST=selenium-hub-bad
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444